### PR TITLE
wallet not connected

### PR DESCRIPTION
**Pull request by luka1993**
My wallet isnt connected i mined for about 30 hours and everything worked just fine,then wallet disconnected and won't connect again

### CODE REVIEW

**Comment by citizenking** [comment]
I can't even connect my electrum-XVG  wallet

**Comment by Dule-martins** [comment]
Please help, i cannot connected to a server on my verge electrum wallet 2.4.1

**Comment by justinvforvendetta** [comment]
and you tried the servers we posted today on twitter?

**Comment by citizenking** [comment]
Thanks the servers worked.

**Comment by Semakr** [comment]
I have a problem! I mine verge for several days and see that
1) Verge electrum is always disconnected
2) coins go to wallet once a day
3) not all coins which were departured from pull server arrived on my wallet. For example i mined about 500 verge coins but on transactions i see +0! WTF? What should i do!?!?

**Comment by Emerald25** [comment]
my verge electrum wallet 2.4.1 cannot connect to a server about a week

**Comment by Emerald25** [comment]
Thanks, used your update)

**Comment by bitspill** [comment]
Use an [Issue](https://github.com/doged/electrum-doged/issues) not a Pull Request for support/troubleshooting/errors. Pull requests are for submitting fixes and/or updates to the code.

**Pull request closed without merging**
